//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChameleonCK.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChameleonCK.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cck_logo {
            get {
                object obj = ResourceManager.GetObject("cck_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily configurable chroma key..
        /// </summary>
        internal static string m64mm_desc {
            get {
                return ResourceManager.GetString("m64mm_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open ChameleonCK.
        /// </summary>
        internal static string m64mm_open {
            get {
                return ResourceManager.GetString("m64mm_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking….
        /// </summary>
        internal static string updates_checking_string {
            get {
                return ResourceManager.GetString("updates_checking_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_latest {
            get {
                object obj = ResourceManager.GetObject("updates_latest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-to-date.
        /// </summary>
        internal static string updates_latest_string {
            get {
                return ResourceManager.GetString("updates_latest_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_outdated {
            get {
                object obj = ResourceManager.GetObject("updates_outdated", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        internal static string updates_outdated_string {
            get {
                return ResourceManager.GetString("updates_outdated_string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_refresh {
            get {
                object obj = ResourceManager.GetObject("updates_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap updates_unknown {
            get {
                object obj = ResourceManager.GetObject("updates_unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not check if you have the latest version.
        ///
        ///Possible reasons:
        ///• The add-on has no access to the internet.
        ///• You&apos;ve checked for updates too frequently (can lead to temporarily exceeding GitHub&apos;s API rate limit).
        ///
        ///Would you like to open the latest release&apos;s page on GitHub in your browser?.
        /// </summary>
        internal static string updates_unknown_elaborate {
            get {
                return ResourceManager.GetString("updates_unknown_elaborate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t check for updates.
        /// </summary>
        internal static string updates_unknown_string {
            get {
                return ResourceManager.GetString("updates_unknown_string", resourceCulture);
            }
        }
    }
}
